env:
  mocha: true
  protractor: true
  es6: true

extends: 'eslint:recommended'

plugins: ['mocha']

globals:
  window: true
  require: true
  angular: true
  inject: true
  should: true
  sinon: true

parserOptions:
  ecmaVersion: 6
  sourceType: module

rules:
  strict: [2, 'function']
  quotes: [1, 'single', { avoidEscape: true }]
  camelcase: 2
  indent: [2, 2]
  new-cap:
    - 2
    - {"newIsCap": true, "capIsNew": false}
  no-mixed-spaces-and-tabs: 2
  no-multiple-empty-lines: 1
  no-trailing-spaces: 2
  keyword-spacing: 2
  space-before-blocks: 1
  space-before-function-paren: 1
  space-infix-ops: 2
  brace-style: [2, '1tbs', { allowSingleLine: true }]
  semi: 2
  block-scoped-var: 2
  consistent-return: 2
  curly: 2
  eqeqeq: 2
  guard-for-in: 2
  no-else-return: 0
  no-loop-func: 2
  vars-on-top: 0
  no-debugger: 1
  no-cond-assign: 2
  no-extra-parens: 0
  no-console: 1
  no-extra-semi: 2
  no-irregular-whitespace: 2
  dot-notation:
    - 2
    - {"allowPattern": "^[a-z]+(_[a-z]+)+$"}
  comma-dangle:
    - 1
    - only-multiline
  mocha/handle-done-callback: 2
  mocha/max-top-level-suites: [1, {limit: 1}]
  mocha/no-exclusive-tests: 1
  mocha/no-global-tests: 2
  mocha/no-nested-tests: 2
  mocha/no-pending-tests: 1
  mocha/no-skipped-tests: 1
  mocha/no-top-level-hooks: 2
